---
- hosts: localhost
  gather_facts: no
  remote_user: root
  vars:
    mongo_user: admin
    mongo_password: admin123 
    git_repo_folder: "/home/vagrant/checkbox.io"
    ansible_python_interpreter: /usr/bin/python3
  environment:
    MONGO_PORT: 3002
    MONGO_IP: 127.0.0.1
    MONGO_USER: "{{ mongo_user }}"
    MONGO_PASSWORD: "{{ mongo_password }}" 
  
  tasks:
  
  - name: install mongodb, nodejs, npm, nginx and pip3
    become: yes
    become_method: sudo
    apt: pkg={{ item }} state=installed update_cache=true cache_valid_time=36000
    with_items: 
    - nodejs
    - npm
    - nginx
  
  - name: clone checkbox.io repo
    git:
      repo: "https://github.com/chrisparnin/checkbox.io.git"
      dest: "{{ git_repo_folder }}"
      force: yes
  
  - name: copy nginx.conf
    become: yes
    become_method: sudo
    copy:
      remote_src: true
      src: "{{ git_repo_folder }}/local-conf/nginx.conf"
      dest: /etc/nginx/nginx.conf
  
  - name: copy local_conf/default
    become: yes
    become_method: sudo
    copy:
      remote_src: true
      src: "{{ git_repo_folder }}/local-conf/default"
      dest: /etc/nginx/sites-available/default
  
  - name: update root path in default file
    become: yes
    become_method: sudo
    lineinfile:
      path: /etc/nginx/sites-available/default
      regexp: 'root*'
      line: "root {{ git_repo_folder }}/public_html/;"
  
  - name: Install Node Modules
    shell: cd {{ git_repo_folder }}/server-side/site ; npm install
    become: yes
  
  - name: Start Node JS
    shell: nohup node server.js &
    become: yes
  
  - name: restart nginx
    become: yes
    become_method: sudo
    service:
      name: nginx
      state: restarted