---
- name: Install packages
  apt: 
    pkg: "{{ item }}"
    state: present
  with_items:
    - python-pip
    - nginx

- name: Add the NodeSource package signing key
  apt_key:
    url: "{{ node_key }}"
    state: present

- name: Add nodejs repo
  apt_repository:
    repo: "{{node_repo}}"
    state: present

- name: Install nodejs
  apt:
    pkg: nodejs
    state: present

- name: Clone repo
  git:
    repo: "{{ checkbox_repo }}"
    dest: "{{ checkbox_dest }}"

- name: Install local node modules
  npm:
    path: "{{ checkbox_dest }}/server-side/site"

- name: Install forever
  npm:
    name: forever
    global: yes
    state: present

- name: Set environment variables
  blockinfile:
    path: /etc/environment
    block: |
      export MONGO_IP=127.0.0.1
      export MONGO_PORT=3002
      export MONGO_USER="admin"
      export MONGO_PASSWORD="admim123"
    create: yes
    state: present

- name: Copy default for nginx
  template:
    src: default.jj2
    dest: /etc/nginx/sites-available/default

- name: Copy nginx config
  copy:
    src: "{{ checkbox_dest }}/local-conf/nginx.conf"
    dest: /etc/nginx/nginx.conf
    remote_src: yes

- name: Restart nginx
  service:
    name: nginx
    state: restarted

- name: Create MongoDB directory
  file:
    path: /data/db
    state: directory
    mode: 0777

- name: Stop all forever scripts
  command: forever stopall

- name: Start server.js using forever
  command: forever start server.js
  args:
    chdir: "{{ checkbox_dest }}/server-side/site/"